# Generated by Django 3.2 on 2021-04-29 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bb',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
