# Generated by Django 3.2 on 2021-05-04 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0003_auto_20210504_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='bb',
            name='slug',
            field=models.SlugField(default=1, unique_for_date='publish'),
            preserve_default=False,
        ),
    ]
