# Generated by Django 3.2 on 2021-05-04 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0004_bb_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bb',
            name='slug',
        ),
    ]
